FROM golang:1.27-trixie AS builder

WORKDIR /go/src/github.com/cerberauth/pashly

COPY go.mod go.mod
COPY go.sum go.sum

ENV CGO_ENABLED 0
ENV GO111MODULE on

RUN go mod download

COPY . .

RUN go build -o /usr/bin/pashly .

FROM gcr.io/distroless/static-debian13:nonroot AS runner

COPY --from=builder --chown=nonroot:nonroot /usr/bin/pashly /usr/bin/pashly

ENTRYPOINT ["pashly"]
CMD ["pashly"]
